# County API Field Mappings

cook_county:
  base_url: "https://datacatalog.cookcountyil.gov/api/v2"
  auth_type: "api_key"
  field_mappings:
    property_id: "pin"
    address: "property_address"
    city: "municipality"
    state: "IL"
    zip_code: "zip"
    property_type: "class"
    land_area: "land_square_feet"
    building_area: "building_square_feet"
    year_built: "year_constructed"
    assessed_value: "total_assessed_value"
    last_sale_date: "last_sale_date"
    last_sale_price: "last_sale_amount"
    image_url: "property_image_url"
    additional_images: "additional_images"
  endpoints:
    properties: "/resource/uzyt-m557.json"
    assessments: "/resource/bcnw-s8k5.json"
    sales: "/resource/wvhk-k5uv.json"

dallas_county:
  base_url: "https://www.dallascad.org/api"
  auth_type: "oauth2"
  field_mappings:
    property_id: "account_number"
    address: "situs_address"
    city: "situs_city"
    state: "TX"
    zip_code: "situs_zip"
    property_type: "state_code"
    land_area: "land_size"
    building_area: "total_area"
    year_built: "year_built"
    assessed_value: "assessed_val"
    last_sale_date: "deed_date"
    last_sale_price: "sale_price"
    image_url: "property_photo_url"
    additional_images: "photo_urls"
  endpoints:
    properties: "/property"
    assessments: "/assessment"
    sales: "/sales"

la_county:
  base_url: "https://assessor.lacounty.gov/api/v1"
  auth_type: "api_key"
  field_mappings:
    property_id: "ain"
    address: "situs_street_address"
    city: "situs_city"
    state: "CA"
    zip_code: "situs_zip_code"
    property_type: "use_type"
    land_area: "lot_size_sqft"
    building_area: "improvement_size"
    year_built: "year_built"
    assessed_value: "total_value"
    last_sale_date: "recording_date"
    last_sale_price: "sale_amount"
    image_url: "image_url"
    additional_images: "image_urls"
  endpoints:
    properties: "/property-assessment"
    assessments: "/assessment-roll"
    sales: "/property-sales"

# Common field types and validations
field_types:
  property_id: "string"
  address: "string"
  city: "string"
  state: "string"
  zip_code: "string"
  property_type: "string"
  land_area: "float"
  building_area: "float"
  year_built: "integer"
  assessed_value: "float"
  last_sale_date: "date"
  last_sale_price: "float"

# Data validation rules
validation_rules:
  year_built:
    min: 1800
    max: 2024
  land_area:
    min: 0
    max: 10000000  # 10M sq ft
  building_area:
    min: 0
    max: 5000000   # 5M sq ft
  assessed_value:
    min: 0
    max: 1000000000  # $1B
  last_sale_price:
    min: 0
    max: 1000000000  # $1B 